server:
  port: 8080
spring:
  application:
    name: order-service
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
  redis:
    host: ${SPRING_REDIS_HOST:redis}
    port: ${SPRING_REDIS_PORT:6379}
    connect-timeout: 15000ms
    lettuce:
      retry:
        enabled: true
        max-attempts: 10
        initial-backoff: 500ms
        max-backoff: 3000ms
  
  datasource:
    url: ${SUPABASE_ORDER_URL}
    username: ${SUPABASE_ORDER_USER}
    password: ${SUPABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
order:
  shipping:
    fixed-cost: 30000
    free-threshold: 500000
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

# Feign configuration
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

vnpay:
  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  tmn-code: 4ZGR78SD
  hash-secret: GZIZ4BR748ZDKILM6EPFHJXCG8189T19
  return-url: http://localhost:8080/payments/vnpay-callback
  version: 2.1.0

logging:
  level:
    com.datn.order_service: DEBUG
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.springframework.security.web.FilterChainProxy: DEBUG

web:
  url: "http://localhost:3000"

cloudinary:
  cloud_name: dtvs3rgbw
  api_key: "624517127684593"
  api_secret: "fm7VXb2cPfELubipKJ8wsNjmOBU"



