spring:
  application:
    name: cart-service
  datasource:
    url: ${SUPABASE_CART_URL}
    username: ${SUPABASE_CART_USER}
    password: ${SUPABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 0
      idle-timeout: 120000
      max-lifetime: 300000
      connection-timeout: 20000
      leak-detection-threshold: 60000
      pool-name: AuthHikariPool
      auto-commit: true
      validation-timeout: 5000
      test-on-borrow: true

  redis:
    host: ${SPRING_REDIS_HOST:redis}
    port: ${SPRING_REDIS_PORT:6379}
    connect-timeout: 15000ms
    lettuce:
      retry:
        enabled: true
        max-attempts: 10
        initial-backoff: 500ms
        max-backoff: 3000ms
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

# Feign configuration
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: BASIC

logging:
  level:
    com.datn.cart_service: DEBUG
    org.hibernate.SQL: DEBUG